### ISSUE TITLE
Languages

### ISSUE THREAD

**Issue by grandmotivator** [Montelibero/app-mtla-me#1]
Добавить возможность выбора языка для интерфейса, для начала хотя бы подключить языки английский и русский.

По умолчанию использовать язык браузера пользователя.

При переключении языка, сохранять выбор в браузере пользователя. В дальнейшем возможно появлении других опций и настроек для пользователя которые будут сохраняться в браузере пользователя.

**Comment by sozidatel** [comment]
Реализовано в пулреквесте #7
